- app/controllers/SchemeBankAccountListController.scala
- app/viewmodels/govuk/ListWithActionsFluency.scala
- app/viewmodels/models/ListViewModel.scala
- app/views/ListView.scala.html
- conf/messages.en
- test-utils/generators/ViewModelGenerators.scala
- test/views/ListViewSpec.scala
> PSR-87 Add aria visually hidden text to change and remove links

- .g8/yesNoPage/app/controllers/$className$Controller.scala
- .g8/yesNoPage/generated-test/controllers/$className$ControllerSpec.scala
- app/controllers/CheckReturnDatesController.scala
- app/controllers/DoesSchemeMemberHaveNINOController.scala
- app/forms/YesNoPageFormProvider.scala
- app/navigation/Navigator.scala
- app/pages/NationalInsuranceNumberPage.scala
- app/viewmodels/govuk/RadiosFluency.scala
- app/viewmodels/models/YesNoPageViewModel.scala
- app/views/YesNoPageView.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/ControllerBehaviours.scala
- test/controllers/DoesSchemeMemberHaveNINOControllerSpec.scala
- test/pages/NationalInsuranceNumberPageSpec.scala
- test/views/YesNoPageViewSpec.scala
name is currently hard coded as previous page hasn't been completed
> PSR-112 Added NI page

- app/navigation/nonsipp/LoansMadeOrOutstandingNavigator.scala
- app/pages/nonsipp/loansmadeoroutstanding/AmountOfTheLoanPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/AreRepaymentsInstalmentsPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/CompanyRecipientCrnPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/CompanyRecipientNamePage.scala
- app/pages/nonsipp/loansmadeoroutstanding/DatePeriodLoanPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/IndividualRecipientNamePage.scala
- app/pages/nonsipp/loansmadeoroutstanding/IndividualRecipientNinoPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/InterestOnLoanPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/IsMemberOrConnectedPartyPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/LoansMadeOrOutstandingPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/OtherRecipientDetailsPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/OutstandingArrearsOnLoanPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/PartnershipRecipientUtrPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/RecipientSponsoringEmployerConnectedPartyPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/RemoveLoanPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/SecurityGivenForLoanPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/WhoReceivedLoanPage.scala
- app/pages/nonsipp/loansmadeoroutstanding/package.scala
- test-utils/generators/ModelGenerators.scala
- test/controllers/ControllerBaseSpec.scala
- test/controllers/nonsipp/loansmadeoroutstanding/RecipientSponsoringEmployerConnectedPartyControllerSpec.scala
- test/pages/nonsipp/loansmadeoroutstanding/WhoReceivedLoanPageSpec.scala
Also updated the spreadsheet with new keys https://docs.google.com/spreadsheets/d/1avFBSMvhqHlXl9B27UNlAKw5YXvuv4rPe37wna7ogBI/edit#gid=0
> PSR-265 Amended loans page cache keys to align with ETMP submission

- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/PSR-310 changing the error message
> changing the error message

- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/PSR-309 PSR-309 changing the message also for the UK Partnership side
> PSR-309 Message changed. It cannot be a collateral effect of PSR-310

- conf/messages.en
PSR-302 as the Doc/ticket requested https://docs.google.com/document/d/1VKy1RMKgFk8jLMLflygoWaPBBHp-t4GWKWFUIVxRImI/edit the error has been changed.
> PSR-302 Error message changed according to the new regex

- app/controllers/nonsipp/memberdetails/CheckMemberDetailsFileController.scala
- app/controllers/nonsipp/memberdetails/MemberDetailsController.scala
- app/forms/mappings/errors/DateFormErrors.scala
- app/services/MemberDetailsUploadValidator.scala
- test/controllers/nonsipp/memberdetails/CheckMemberDetailsFileControllerSpec.scala
- test/controllers/nonsipp/memberdetails/MemberDetailsControllerSpec.scala
- test/services/MemberDetailsUploadValidatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-306 So far the user could Input aDOB that exceeded the tax year details, this PR is to fix it.
> PSR-306 Fix DOB after tax details

- app/controllers/nonsipp/memberdetails/MemberDetailsController.scala
- app/services/MemberDetailsUploadValidator.scala
- conf/messages.en
- test/controllers/nonsipp/memberdetails/MemberDetailsControllerSpec.scala
- test/services/MemberDetailsUploadValidatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-306 Adding the date into the error message
> PSR 306 - Implementing last valid date into the error message

- app/config/Constants.scala
- app/controllers/nonsipp/landorproperty/LandOrPropertyLeaseDetailsController.scala
- app/controllers/nonsipp/landorproperty/WhenDidSchemeAcquireController.scala
- app/controllers/nonsipp/loansmadeoroutstanding/DatePeriodLoanController.scala
- app/controllers/nonsipp/loansmadeoroutstanding/LoansCYAController.scala
- app/controllers/nonsipp/memberdetails/MemberDetailsController.scala
- conf/messages.en
- test-utils/generators/BasicGenerators.scala
- test/controllers/ControllerBaseSpec.scala
- test/controllers/nonsipp/landorproperty/LandOrPropertyLeaseDetailsControllerSpec.scala
- test/controllers/nonsipp/landorproperty/WhenDidSchemeAcquireControllerSpec.scala
- test/controllers/nonsipp/loansmadeoroutstanding/DatePeriodLoanControllerSpec.scala
- test/controllers/nonsipp/loansmadeoroutstanding/LoansCYAControllerSpec.scala
- test/controllers/nonsipp/memberdetails/MemberDetailsControllerSpec.scala
- test/forms/DatePageFormProviderSpec.scala
- test/forms/NameDOBFormProviderSpec.scala
- test/forms/behaviours/FieldBehaviours.scala
Resolves also:
PSR-449
PSR-446
PSR-435
PSR-451
> PSR-299 Validation required for minimal date value

- app/config/Constants.scala
- app/controllers/nonsipp/moneyborrowed/BorrowedAmountAndRateController.scala
- app/navigation/nonsipp/MoneyBorrowedNavigator.scala
- app/pages/nonsipp/moneyborrowed/BorrowedAmountAndRatePage.scala
- app/pages/nonsipp/moneyborrowed/package.scala
- app/viewmodels/models/MultipleQuestionsViewModel.scala
- conf/messages.en
- conf/moneyborrowed.routes
- test/controllers/nonsipp/moneyborrowed/BorrowedAmountAndRateControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-348
> PSR-348 Money borrowed and interest rates

- app/controllers/nonsipp/moneyborrowed/BorrowInstancesListController.scala
As PSR-360 got merged some of my code was behaving unexpectedly. This will fix the problem.
> PSR-359 Refactored to better suit the new Remove Controller

- app/controllers/nonsipp/loansmadeoroutstanding/IsIndividualRecipientConnectedPartyController.scala
- conf/messages.en
- test/controllers/nonsipp/loansmadeoroutstanding/IsIndividualRecipientConnectedPartyControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-479 Added some details about what actually a connected party is
> PSR-479 Connected party information

- app/controllers/nonsipp/landorpropertydisposal/HowWasPropertyDisposedOfController.scala
- app/controllers/nonsipp/landorpropertydisposal/TotalProceedsSaleLandPropertyController.scala
- app/views/MoneyView.scala.html
PSR-534 a11y fix for issue Element “p” not allowed as child of element “label”
> PSR-534 a11y fix for issue Element “p” not allowed as child of element

- app/config/Constants.scala
- app/controllers/nonsipp/memberpayments/UnallocatedEmployerAmountController.scala
- app/navigation/nonsipp/UnallocatedEmployerContributionsNavigator.scala
- app/pages/nonsipp/memberpayments/UnallocatedEmployerAmountPage.scala
- conf/app.routes
- conf/messages.en
- test/controllers/nonsipp/memberpayments/UnallocatedEmployerAmountControllerSpec.scala
- test/navigation/nonsipp/UnallocatedEmployerContributionsControllerNavigatorSpec.scala
- test/navigation/nonsipp/UnallocatedEmployerContributionsNavigatorSpec.scala
- test/pages/nonsipp/memberpayments/UnallocatedEmployerAmountPageSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-384 Unallocated amount page
> PSR-384 Unallocated Amount

- app/controllers/nonsipp/memberpayments/RemoveUnallocatedAmountController.scala
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/PSR-581 Going back after removing the unallocated amount now redirects to the tasklist
> PSR-581 fixing back after removal

- app/controllers/nonsipp/TaskListController.scala
- app/navigation/nonsipp/ReceiveTransferNavigator.scala
- test/navigation/nonsipp/ReceiveTransferNavigatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-395 Apparently @westwater already made this page, so I am just doing some changes to the navigation really
> PSR-395 Adjusting transfer received

- app/controllers/nonsipp/membercontributions/ReportMemberContributionListController.scala
- app/navigation/nonsipp/MemberContributionsNavigator.scala
- app/pages/nonsipp/memberpayments/ReportMemberContributionListPage.scala
- conf/membercontributions.routes
- conf/messages.en
- test/controllers/nonsipp/membercontributions/ReportMemberContributionListControllerSpec.scala
- test/navigation/nonsipp/MemberContributionsNavigatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-389
> PSR-389 Member-payment contribution list

- app/controllers/auth/SignedOutController.scala
- app/controllers/nonsipp/landorpropertydisposal/LandOrPropertyDisposalAddressListController.scala
- test/controllers/nonsipp/landorpropertydisposal/LandOrPropertyDisposalAddressListControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-481 If the user says that no portion of the properties are held, this will make sure the address doesn't pop in the list
> PSR 481 remove address from list

- app/controllers/nonsipp/landorpropertydisposal/LandOrPropertyDisposalAddressListController.scala
- app/controllers/nonsipp/membertransferout/SchemeTransferOutController.scala
- app/controllers/nonsipp/membertransferout/WhatYouWillNeedTransferOutController.scala
- app/navigation/nonsipp/TransferOutNavigator.scala
- app/pages/nonsipp/membertransferout/SchemeTransferOutPage.scala
- app/pages/nonsipp/membertransferout/WhatYouWillNeedTransferOutPage.scala
- conf/app.routes
- conf/memberpayments_transferout.routes
- conf/messages.en
- test/controllers/nonsipp/membertransferout/SchemeTransferOutControllerSpec.scala
- test/controllers/nonsipp/membertransferout/WhatYouWillNeedTransferOutControllerSpec.scala
- test/navigation/nonsipp/TransferOutNavigatorSpec.scala
- test/pages/nonsipp/membertransfersout/SchemeTransferoutPageSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-511 What you will need type of page for transfer out
> PSR-511 What You Will need transfer out

- app/controllers/nonsipp/membertransferout/ReceivingSchemeNameController.scala
- app/navigation/nonsipp/TransferOutNavigator.scala
- app/pages/nonsipp/membertransferout/ReceivingSchemeNamePage.scala
- app/pages/nonsipp/membertransferout/package.scala
- app/viewmodels/InputWidth.scala
- app/views/TexInputViewWidth40.scala.html
- conf/memberpayments_transferout.routes
- conf/messages.en
- test/controllers/nonsipp/membertransferout/ReceivingSchemeNameControllerSpec.scala
- test/pages/nonsipp/membertransfersout/ReceivingSchemeNamePageSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-513
> PSR-513 receiving scheme name

- app/controllers/nonsipp/membertransferout/ReceivingSchemeTypeController.scala
- app/navigation/nonsipp/TransferOutNavigator.scala
- app/pages/nonsipp/membertransferout/ReceivingSchemeTypePage.scala
- conf/memberpayments_transferout.routes
- conf/messages.en
- test/controllers/nonsipp/membertransferout/ReceivingSchemeTypeControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-515 Asking the Pension scheme type
> PSR-515 Page completed

- app/controllers/testonly/LandOrPropertyMongoController.scala
- app/models/HowDisposed.scala
- app/models/PensionSchemeType.scala
https://jira.tools.tax.service.gov.uk/browse/PSR-709
> PSR-709 ETMP better reading

- app/controllers/nonsipp/shares/WhatYouWillNeedSharesController.scala
- app/navigation/nonsipp/SharesNavigator.scala
- app/pages/nonsipp/shares/WhatYouWillNeedSharesPage.scala
- conf/messages.en
- conf/shares.routes
- test/controllers/nonsipp/shares/WhatYouWillNeedSharesControllerSpec.scala
- test/navigation/nonsipp/SharesNavigatorSpec.scala
Based on previous branch PSR-565, so currently shows both ticket's changes
> PSR-567 What you will need shares page

- conf/messages.en
- Do you need to report another transfer in for [name of member]?
- Do you need to report another transfer out for [name of member]?
> Updated transfer in and transfers out

- app/controllers/nonsipp/common/CompanyRecipientCrnController.scala
- app/controllers/nonsipp/shares/CompanyNameOfSharesSellerController.scala
- app/controllers/nonsipp/shares/SharesCYAController.scala
- app/controllers/nonsipp/shares/SharesFromConnectedPartyController.scala
- app/controllers/nonsipp/shares/SharesListController.scala
- app/controllers/nonsipp/sharesdisposal/CompanyBuyerCrnController.scala
- app/navigation/nonsipp/SharesDisposalNavigator.scala
- app/navigation/nonsipp/SharesNavigator.scala
- app/pages/nonsipp/common/IdentityTypePage.scala
- app/pages/nonsipp/shares/CompanyNameOfSharesSellerPage.scala
- conf/messages.en
- conf/sharesdisposal.routes
- test/controllers/nonsipp/shares/CompanyNameOfSharesSellerControllerSpec.scala
- test/controllers/nonsipp/sharesdisposal/CompanyBuyerCrnControllerSpec.scala
- test/navigation/nonsipp/SharesDisposalNavigatorSpec.scala
- test/navigation/nonsipp/SharesNavigatorSpec.scala
- test/pages/nonsipp/shares/CompanyNameOfSharesSellerPageSpec.scala
1st commit contains the bug fix for PSR-849
2nd commit contains the implementation of PSR-650
> PSR-650 PSR-849 Buyer Company CRN Number page implementation and Seller Company Name bug fix

- project/AppDependencies.scala
Do not merge before 19th Feb 2024
> Tudor Crown update

- conf/messages.en
- End dates of shares and bonds
- Date and period of loan
- Check your answers page pension payments
> Fixed errors from update based on round 10 of UR

- app/connectors/PSRConnector.scala
- conf/application.conf
PSR-1311 Change to HttpClientV2
> PSR-1311 Change PsrConnector to use HttpClientV2

- conf/messages.en
https://psr-prototype.herokuapp.com/7-0/ss_questions/member_payments/pension_payments/payment_amount  https://psr-prototype.herokuapp.com/7-0/ss_questions/member_payments/pension_payments/check_answers
> Content changes: Changed ‘taxable’ to ‘gross’

- app/config/Constants.scala
- app/controllers/OverviewController.scala
Session details has been added for sipp redirecting.
> PSR-1315 - Added all session details when redirecting to SIPP

- conf/messages.en
Page: What was the total cost of the land or property, in pounds and pence? Change to hint text.
> Content update - Change to hint text

- conf/messages.en
Content changes from 17/7/24 and 18/7/24 Updated total cash and assets minus liabilities questions and hidden text
> Content update - total cash minus liabilities wording

- conf/messages.en
Content update to declaration button text: changed from 'Agree and continue' to 'Agree and submit'
> Content change - button text from 'continue' to 'submit'

- conf/messages.en
text change x3 lines - bonds, shares and other assets.
> Content update to bonds, shares and other assets

- .g8/scripts/updateNavigator
Not worth the time investment as we no longer use these generators - the bug was very minor, it just meant it didn't create a newline after existing routes
> PSR-1482 Removed todos in update navigator

- conf/messages.en
x2 small content updates to shares content.
> Content updates to shares content

- test-utils/generators/BasicGenerators.scala
- test-utils/generators/ViewModelGenerators.scala
- test/transformations/SharesTransformerSpec.scala
- test/views/RadioListViewSpec.scala
> NO-JIRA Fix flaky test

- app/views/ConditionalYesNoPageView.scala.html
- app/views/MultipleQuestionView.scala.html
- app/views/NameDOBView.scala.html
**Issue:**
- [Incorrect error summary link destination](https://github.com/hmrc/accessibility-audits-external/issues/8763)
**Dev Tasks:**
> PSR-1678 | [Accessibility] Issue: Incorrect error summary link destination #8763

- conf/messages.en
Linked to https://github.com/hmrc/accessibility-audits-external/issues/8754 accessibility issue.
> Content update to security error sign out page

- app/config/Constants.scala
- app/controllers/nonsipp/loansmadeoroutstanding/LoansListController.scala
- app/controllers/nonsipp/otherassetsheld/IncomeFromAssetController.scala
- app/controllers/nonsipp/otherassetsheld/OtherAssetsListController.scala
- app/controllers/nonsipp/shares/SharesListController.scala
- app/utils/nonsipp/MemberCountUtils.scala
- app/utils/nonsipp/TaskListStatusUtils.scala
- app/utils/nonsipp/TaskListUtils.scala
- conf/messages.en
- test/controllers/nonsipp/loansmadeoroutstanding/LoansListControllerSpec.scala
- test/controllers/nonsipp/otherassetsheld/OtherAssetsListControllerSpec.scala
- test/utils/nonsipp/TaskListStatusUtilsSpec.scala
Edit: `PSR-1637` has been merged into `main`, so this branch is safe to merge once review and QA have been completed.
---
~**Note: this PR should not be merged until after `PSR-1637` has been merged into `main`.**~
~This branch was originally created from `PSR-1637`, not `main`, but once `PSR-1637` has been merged into `main`, this PR will automatically update its base, and then it can be safely merged into `main`.~
> PSR-1588 | Implement OAs PrePop List page

- app/views/components/OverviewTable.scala.html
- app/views/components/OverviewTableThreeColumns.scala.html
- test/controllers/OverviewControllerSpec.scala
[Accessibility] Issue: Accessible name implementation on table wrapper (P1) #9034
> [PSR-1826] Accessible name implementation on table wrapper

- app/utils/nonsipp/TaskListUtils.scala
- test/utils/nonsipp/TaskListUtilsSpec.scala
* show view only declaration section if there ios only one version and no changes in local user answers
> PSR-2114: update task list declaration section
